name: Build and Push to Docker
on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running Docker
        run: |
          docker build . --file Dockerfile --tag flask-docker
          docker run flask-docker:latest
